### ISSUE TITLE
more specific examples

### ISSUE THREAD

**Issue by laserlab** [ubsuny/MLWobbleCompensation-CP2P2024#5]
https://github.com/ubsuny/MLFringe-Contrast-CP2P2024/blob/2492e3a61cf4dfc9ad530770b6bdd274d1bb9cd1/documentation.md?plain=1#L3

Can you give some more specific examples?

**Comment by uarif** [comment]
@laserlab , I will be using np.complex64, and maybe np.complex128 or even np.complex256. And also, float64 and so on. As I have huge data so I need to use them. Also I have complex exponentials and I need complex data types.
